name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar arquivos
        run: echo "CI rodando com sucesso!"

      - name: Notificar Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" -X POST -d "{\"content\": \"🚀 Deploy realizado com sucesso no calculadora-cicd!\"}"