name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Verificar arquivos
        run: echo "CI rodando com sucesso!"

      - name: Notificar Discord
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 CI executado no repositório calculadora-cicd!"}' \
          "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test